version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    versioning-strategy: increase # Update package.json too
    groups:
      patterns:
        update-types:
          - patch
          - minor
