platform:
- x64
environment:
  nodejs_version: "6"
  matrix:
  - node_installer: yarn
cache:
- 'node_modules'
- '%USERPROFILE%\.electron'
branches:
  only:
  - master

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g npm@4
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm test -- --installer=%node_installer%

build: off
