platform:
- x64
environment:
  nodejs_version: "6"
  matrix:
  - node_installer: yarn
cache:
- 'node_modules'
- '%USERPROFILE%\.electron'
branches:
  only:
  - master

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- yarn

test_script:
- node --version
- yarn --version
- yarn test --installer=%node_installer%

build: off
