language: node_js
node_js:
  - "6"
os:
- linux
- osx
dist: trusty
sudo: required

services:
- docker

env:
  matrix:
  - NODE_INSTALLER=npm
  - NODE_INSTALLER=yarn

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

script: ci/script.sh
