name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-installer: [npm, yarn]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install bolt
      run: npm install -g bolt
    - name: Install
      run: bolt
    - name: Lint
      run: bolt lint
    - name: Build
      run: bolt build
    - name: Test
      run: bolt coverage
      env:
        CI: true
        DEBUG: electron-installer-snap:snapcraft
        NODE_INSTALLER: ${{ matrix.node-installer }}
    - name: Codecov
      run: bolt codecov
