name: API Documentation

on:
  workflow_dispatch:
  push:
    tags:
      - v7.**

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.GH_APP_CREDS }}
          export-git-user: true

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Use Node.js LTS
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20.x
          cache: yarn

      - name: Build
        shell: bash
        run: |
          yarn
          yarn docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: ./docs
          cname: js.electronforge.io
          user_name: ${{ env.GIT_COMMITTER_NAME }}
          user_email: ${{ env.GIT_COMMITTER_EMAIL }}
