name: API Documentation

on:
  push:
    tags:
      - v6.**

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.GH_APP_CREDS }}
          export-git-user: true

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Use Node.js LTS
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 20.x
          cache: yarn

      - name: Build
        shell: bash
        run: |
          yarn
          yarn docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: ./docs
          cname: js.electronforge.io
          user_name: ${{ env.GIT_COMMITTER_NAME }}
          user_email: ${{ env.GIT_COMMITTER_EMAIL }}
